pipeline {
    agent any
    stages {
        stage('Clone stage') {
            steps {
                echo 'Hello Nguyen Manh Dung'
            }
        }
        stage('Check Maven Version') {
            steps {
                script {
                    sh '/opt/apache-maven-3.9.6/bin/mvn --version'
                }
            }
        }
        stage('Build Jar') {
		    steps {
		        script {
		            
		            sh 'ls'          
		            dir('test') {
		                sh 'ls'
		                sh 'mvn clean install'
		            }
		        }
		    }
		}
		stage('Build image') {
		    steps {
		        script {
		       		sh 'ls' 
			        dir('test') {
			            withDockerRegistry(credentialsId: 'docker-hub', url: 'https://index.docker.io/v1/') {
		          		app = docker.build("nguyenmanhdung/jenkins-helloword:0.0.1")
		          		sh 'docker push nguyenmanhdung/jenkins-helloworld:0.0.1'	          		
						}
			        }
		        }
		    }
		}
		
		
	

		

    // stage('Build image') {
    //     steps {
    //         withDockerRegistry(credentialsId: 'dockerhub-nmd', url: 'https://index.docker.io/v1/') {
    //             echo 'Bắt đầu tạo image'
    //             sh 'docker build -t nguyenmanhdung/jenkins-helloworl:0.0.1 .'
    //             echo 'Tạo image thành công'
    //             echo 'Bắt đầu push image'
    //             sh 'docker push nguyenmanhdung/jenkins-helloworl:0.0.1'
    //             echo 'Push image thành công'
    //         }
    //     }
    // }
    }
}
