pipeline {
    agent any
    environment {
        REMOTE_SERVER_IP = '192.168.10.56'
        REMOTE_SERVER_SSH_PORT = '22'
        REMOTE_SERVER_USER = 'rnd'
        REMOTE_SERVER_PASSWORD = 'abcd456789'
        IMAGE_VERSION = 'nguyenmanhdung/jenkins-helloworld:0.0.2'
    }
    stages {
        stage('Clone stage') {
            steps {
                echo 'Hello Nguyen Manh Dung'
            }
        }
        stage('Check Maven Version') {
            steps {
                script {
                    sh '/opt/apache-maven-3.9.6/bin/mvn --version'
                }
            }
        }
        stage('Build Jar') {
		    steps {
		        script {
		            
		            sh 'ls'          
		            dir('test') {
		                sh 'ls'
		                sh '/opt/apache-maven-3.9.6/bin/mvn clean install'
		            }
		        }
		    }
		}
		stage('Build image') {
		    steps {
		        script {
		       		sh 'ls' 
			        dir('test') {
			           	withDockerRegistry(credentialsId: 'docker-nmd', url: 'https://index.docker.io/v1/') {
		          		app = docker.build("nguyenmanhdung/jenkins-helloworld:0.0.2")
		          		sh 'docker push nguyenmanhdung/jenkins-helloworld:0.0.2'	          		
						}
			        }
		        }
		    }
		}
		stage('Run Container in Remote Server') {
            steps {
                script {                
                	echo 'Kết nối remote server'
                        script = "sshpass -p ${REMOTE_SERVER_PASSWORD} ssh -o StrictHostKeyChecking=no ${REMOTE_SERVER_USER}@${REMOTE_SERVER_IP} -p ${REMOTE_SERVER_SSH_PORT}"                        
                    echo 'Kết nối {REMOTE_SERVER_IP} thành công'
                    echo 'Pull Image ${IMAGE_VERSION}'
                        script += " docker pull ${IMAGE_VERSION}" 
                    echo 'Pull Image ${IMAGE_VERSION} thành công'
                    echo 'Run Image ${IMAGE_VERSION}'                         
                        script += " docker run -d -p 8080:8080 ${IMAGE_VERSION}"
                    echo 'Run Image ${IMAGE_VERSION} thành công'     
                        // script += " other_commands_here"
                }
            }
        }
    }
}
